[package]
name = "nle_media"
version = "0.1.0"
edition = "2021"

[dependencies]
# ffmpeg-next = "6.0"
wgpu = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
